version: '3.8'
services:
    notification-service:
        build: .
        volumes:
            - ./src:/usr/app/src
        ports:
            - '3000:3000'
        depends_on:
            - mongo
            - rabbitmq
    mongo:
        image: mongo:4.2.8-bionic
        ports:
            - '3001:27017'
    rabbitmq:
        image: rabbitmq:3.8.5
        ports:
            - '5672:5672'
    # mongo-seed:
    #     build: ./seed
    #     links:
    #         - mongo
