name: Docker Testing

on:
    - push
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_ORIGIN: ${{ secrets.ORIGIN }}
                  envkey_PORT: ${{ secrets.PORT }}
                  envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
                  envkey_CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
                  envkey_DB_URL: ${{ secrets.DB_URL }}
                  envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  envkey_MAILGUN_ORIGIN: ${{ secrets.MAILGUN_ORIGIN }}
                  envkey_MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
                  envkey_MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
                  envkey_MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL }}
                  file_name: .env
            - name: Build + Test in Docker
              run: |
                  docker-compose --file docker-compose.test.yaml build sut
                  docker-compose --file docker-compose.test.yaml run sut
